### ISSUE TITLE
Value Lists not coming through

### ISSUE THREAD

**Issue by joleksow** [airmoi/FileMaker#4]
Hello,

When retrieving a record from a layout that is definitely using a value list for some of its values (as a radio button set), the returned record's layout object does not include anything in the valueLists or valueListTwoFields arrays. Do you have any idea why it might not be coming through or any advice on how to troubleshoot?

Thanks,
John

**Comment by airmoi** [comment]
Hi Joleksow,

Thanks again for your feedback. I've found that when layout's extended info were already retrieved,  the API didn't load it again so the value list wasn't refresh as expected.

I've fixed it and add a test case for that

Airmoi

**Comment by joleksow** [comment]
Airmoi,

Thanks for your quick attention to this. I updated to the latest release, but am still not getting any value lists returned despite them being used on the layout I'm returning a record from. Any suggestions for how to troubleshoot?

Thanks,
Joleksow

**Comment by airmoi** [comment]
Hi,

Could you post the part of your code where value list are called ?

**Comment by joleksow** [comment]
I've tried it a few ways, mostly through xdebug. When a record is retrieved (airmoir\FileMaker\Object\Record), I can see that the layout object (airmoir\FileMaker\Object\Layout) has two empty arrays named valueLists and valueListTwoFields.

I just noticed that when I run 
```$valueLists = $record->layout->getValueListsTwoFields();```
the layout object's value list arrays are partially populated, but it ends up throwing a FileMakerException of Field not Found. It looks like this is occurring in the RelatedSet's getField method on line 92, and occurs with a specific fieldName, but I'm not sure why it fails at that point.

Is there any other info I could provide that would help you troubleshoot what might be going on?

**Comment by airmoi** [comment]
The getValueListsTwoFields method, when called without a recid won't returns value lists based on relatedset values, that may be why some of your value lists are still empty.
If this is the case, you may use 
```
$valueLists = $record->layout->getValueListsTwoFields($record->recordId);
```

Could you email me a stack trace of the exception and the code used to reproduce the exception ?

**Comment by airmoi** [comment]
I believe I misunderstood your first comment.
The layout object in the a record does not include value lists when a record is return by fms as the FileMaker XML result doesn't contain them.
You where right using the getValueList* methods as it triggers the loadExtendedInfo method which make a new call to fms to retrieve them.

Btw, the exception (field not found) sound to be a different issue than the value list issue.
Are you sure the requested Field is present in the FileMaker's layout you use ?

**Comment by airmoi** [comment]
I've added a getFieldValueListTwoFields method to the Record Object to retrieve a value list associated to a field in FileMaker's layout (work with both simple and related value lists).
You may use it this way : 
```
 $record->getFieldValueListTwoFields('myField');
```

Tell me if it helps

**Comment by joleksow** [comment]
Thanks for your quick attention to this. Unfortunately the new function doesn't seem to solve the issue, though I think it will come in handy once the core issue is resolved.

Here's what seems to be happening:
the setExtendedInfo method in FMPXMLLAYOUT.php is calling $layout_getField. The field that is causing an issue is a field from a related set. The field definitely exists in a portal in the primary record. However, the field doesn't exist in the relatedSet object's fields array. This means that when we get to the line
```return $this->getRelatedSet($relatedSet)->getField($fieldName);```

It's throwing an exception because it can't find the field.

Is there a reason that the relatedSet array wouldn't be getting all the fields included in the portal in the layout? There are 3 total fields in the portal and only the second two are coming through in the relatedSet->fields array.

I hope this makes sense. Let me know if you need any additional details.

**Comment by airmoi** [comment]
There is no apparent reason for that !
What's the name of the incriminate field ?

Could you check the xml returned by fms to see if the field is present in FileMaker's response ?

**Comment by joleksow** [comment]
The issue seems to be specific to the layout I'm trying to work with. I'm planning on moving  the value lists to a separate, simpler layout in order to avoid this issue and also cut down on the amount of data that needs to be returned (the original layout I wanted to work with has lots of portals that aren't relevant to the value list data needed). 

What's the easiest way to check the returned xml, by the way?

**Comment by airmoi** [comment]
The best way is to use the xml publishing engine. You may write your own request in a browser.

Here is sample requests from the official doc (see more info about the xml cwp in the [official doc](https://fmhelp.filemaker.com/docs/14/fr/fms14_cwp_guide.pdf)): 
To retrieve layout information:
http://192.168.123.101/fmi/xml/FMPXMLLAYOUT.xml?-db=employees
&-lay=departments&-view
To retrieve metadata information:
http://192.168.123.101/fmi/xml/fmresultset.xml?-db=employees
&-lay=departments&-view
To find a record by record ID:
http://192.168.123.101/fmi/xml/fmresultset.xml?-db=employees&-lay=family
&-recid=427&-find
